# Generated by Django 4.2.6 on 2024-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_created_at_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='created_another_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
