# Generated by Django 4.2.6 on 2024-02-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_doctorprofile_created_another_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='created_another_at',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='updated_at',
        ),
    ]
